// Package Unit Enums
export const PACKAGE_UNIT = {
    CARTON: 'CARTON',
    PALLET: 'PALLET'
};

// VAT Export Status Enums
export const VAT_STATUS = {
    NOT_ISSUED: 'NOT_ISSUED',
    ISSUED_NOT_PACKAGED: 'ISSUED_NOT_PACKAGED',
    ISSUED_PACKAGED: 'ISSUED_PACKAGED'
};

// Product Code Status Enums
export const PRODUCT_STATUS = {
    ENTERED_WAREHOUSE: 'ENTERED_WAREHOUSE',
    WAITING_FOR_LOADING: 'WAITING_FOR_LOADING',
    LOADING_IN_CHINA: 'LOADING_IN_CHINA',
    CUSTOMS_INSPECTION: 'CUSTOMS_INSPECTION',
    WAITING_FOR_VN_CUSTOMS: 'WAITING_FOR_VN_CUSTOMS',
    CLEARED_CUSTOMS: 'CLEARED_CUSTOMS',
    LOADED: 'LOADED'
};

// Declaration Status Enums
export const DECLARATION_STATUS = {
    EXPECTED_ENTRY: 'EXPECTED_ENTRY'
};

// General Info Source Enums
export const INFO_SOURCE = {
    KHO_TQ: 'KHO_TQ',
    KHO_VN: 'KHO_VN',
    CUSTOMER: 'CUSTOMER',
    EXPECTED_ENTRY: 'EXPECTED_ENTRY'
};
